/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tv_yewai_live_jni_ImageUtilEngine */

#ifndef _Included_tv_yewai_live_jni_ImageUtilEngine
#define _Included_tv_yewai_live_jni_ImageUtilEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spore_jni_ImageUtilEngine
 * Method:    decodeYUV420SP
 * Signature: ([BII)[I
 */
JNIEXPORT jintArray JNICALL Java_tv_yewai_live_jni_ImageUtilEngine_decodeYUV420SP
  (JNIEnv *, jobject, jbyteArray, jint, jint);

//JNIEXPORT jstring JNICALL Java_tv_yewai_live_jni_ImageUtilEngine_call
//        (JNIEnv *,jobject  context ,jstring param1,jstring param2);

#ifdef __cplusplus
}
#endif
#endif
